# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-18 10:03
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('oc_core', '0003_auto_20160217_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navigation',
            name='navigation',
            field=wagtail.wagtailcore.fields.StreamField([(b'menu_block', wagtail.wagtailcore.blocks.StructBlock([(b'title', wagtail.wagtailcore.blocks.CharBlock()), (b'menu_items', wagtail.wagtailcore.blocks.ListBlock(wagtail.wagtailcore.blocks.StreamBlock([(b'link_external', wagtail.wagtailcore.blocks.StructBlock([(b'caption', wagtail.wagtailcore.blocks.CharBlock()), (b'url', wagtail.wagtailcore.blocks.CharBlock()), (b'mega_menu', wagtail.wagtailcore.blocks.BooleanBlock(blank=True, default=False, label=b'Show_in_mega_menu', required=False))])), (b'link_page', wagtail.wagtailcore.blocks.PageChooserBlock())])))]))], blank=True),
        ),
    ]
